version: "3.4"

services:
  frontend:
    image: "node:8"
    # switch to root if global installation is needed:
    user: "root"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ${PWD}:/home/node/app
    ports:
        - "3000:3000"
        - "3001:3001"
    command: "npm start"
